version: 2

jobs:
  build:
    docker:
      - image: node:8.9.1
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install node modules
          command: npm i
      - run:
          name: Run test
          command: npm run ava