name: 'build'
on:
  pull_request:
  push:
    branches:
      - feature/*  # TODO: Replace with `master`

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run doc
